In [26]:
import pandas as pd
pd.__version__

'3.0.6'

In [27]:
df=pd.read_csv('C:\\projects\\ml-zoomcamp-2026\\Homework1\\car_fuel_efficiency_2026.csv')
len(df)

10000

In [28]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [29]:
df['fuel_type'].nunique()

3

In [30]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [31]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [32]:
df['horsepower'].median()

np.float64(254.0)

In [33]:
frequent=df['horsepower'].value_counts().head(1)
frequent

horsepower
252.0    174
Name: count, dtype: int64

In [36]:
df['horsepower'] = df['horsepower'].fillna(frequent.index[0])

In [38]:
df['horsepower'].median()

np.float64(252.0)

In [42]:
df=df[df['origin']=='Asia']
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [45]:
df=df[['vehicle_weight','model_year']]
df

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [48]:
df=df[:7]
df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [49]:
X=df.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [52]:
XTX=X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [54]:
import numpy as np
XTX_inv=np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [55]:
y=np.array([1100,1300,800,900,1000,1100,1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [56]:
w=XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [57]:
w.sum()

np.float64(0.36919696904925486)